# Generated by Django 4.0 on 2021-12-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiendas',
            options={'verbose_name_plural': 'Tiendas'},
        ),
    ]
